### ISSUE TITLE
Controllere USER

### ISSUE THREAD

**Issue by IoanaFeraru** [IoanaFeraru/MTSDbe#20]
- [x] PUT Update user (fara parola, aici nu se pune parola) 
- [x] PUT Update user password
- [x] POST creare provider
- [x] PUT validare provider
- [x] PUT deny provider
- [x] PUT update provider
- [x] GET user 
- [x] GET provider
- [x] GET searchByUsernamePattern
- [x] logare
- [x] GET id ptr user
- [x] GET all users
- [x] GET all providers
- [x] GET id ptr provider

**Comment by Steftrix** [comment]
wow! super team leader 😊
